/* ═══════════════════════════════════════════════════════════════
   Comprehensive NSE Stock Universe for Swing Scanner
   ~800+ stocks covering all segments of the Indian market.
   Excludes: ETFs, InvITs, REITs, suspended stocks.
   ═══════════════════════════════════════════════════════════════ */

// ── Nifty 50 constituents (for optional exclusion) ──
export const NIFTY_50: Set<string> = new Set([
  'RELIANCE','TCS','HDFCBANK','INFY','ICICIBANK','HINDUNILVR','ITC',
  'SBIN','BHARTIARTL','KOTAKBANK','LT','AXISBANK','HCLTECH','TITAN',
  'BAJFINANCE','ASIANPAINT','MARUTI','SUNPHARMA','NESTLEIND','TATAMOTORS',
  'WIPRO','NTPC','POWERGRID','ULTRACEMCO','ADANIPORTS','TATASTEEL',
  'ONGC','JSWSTEEL','TECHM','INDUSINDBK','BAJAJ-AUTO','M&M',
  'COALINDIA','DRREDDY','BPCL','CIPLA','GRASIM','ADANIENT',
  'APOLLOHOSP','EICHERMOT','HEROMOTOCO','DIVISLAB','TATACONSUM',
  'HINDALCO','SBILIFE','BAJAJFINSV','HDFCLIFE','BRITANNIA','SHRIRAMFIN','LTIM',
]);

// ── Known ETFs to exclude ──
export const ETFS: Set<string> = new Set([
  'NIFTYBEES','BANKBEES','JUNIORBEES','GOLDBEES','LIQUIDBEES','SETFNIFTY',
  'SETFNIF50','ICICIBANKP','CPSEETF','BHARAT22ETF','NETFIT','MON100',
  'MAFANG','MASPTOP50','NIF100BEES','SILVERBEES','ITBEES','SETFNN50',
  'SETFNIFBK','HABORETF','SETFGOLD','PSUBNKBEES','NEXT50','MIDCAP',
  'SETF10GILT','MAN50ETF','MONQ50','MIDSMALL','HABORETF',
]);

// ── Full NSE stock universe (~800+ symbols) ──
export const NSE_UNIVERSE: string[] = [
  // === BANKING & FINANCIAL ===
  'HDFCBANK','ICICIBANK','SBIN','KOTAKBANK','AXISBANK','INDUSINDBK',
  'BANDHANBNK','RBLBANK','FEDERALBNK','IDFCFIRSTB','AUBANK','CSBBANK',
  'KARURVYSYA','DCBBANK','UJJIVANSFB','EQUITAS','ESAFSFB','SURYODAY',
  'TMBANK','CITYUNIONBK','SOUTHBANK','IOB','CENTRALBK','MAHABANK',
  'BANKBARODA','CANARABNK','UNIONBANK','INDIANB','PNBHOUSING','UCOBANK',
  'IDBI','J&KBANK','BANKINDIA','PSB',
  // NBFC & Finance
  'BAJFINANCE','BAJAJFINSV','MUTHOOTFIN','MANAPPURAM','CHOLAFIN',
  'SHRIRAMFIN','LICHSGFIN','CANFINHOME','AAVAS','MASFIN','CREDITACC',
  'POONAWALLA','IIFL','PNBHOUSING','MOTILALOFS','ANGELONE',
  'JMFINANCIL','SUNDARMFIN','REPCO','APTUS','HOMEFIRST',
  // Insurance & AMC
  'SBILIFE','HDFCLIFE','ICICIPRULI','STARHEALTH','NIACL','GICRE',
  'LICI','BSE','CDSL','MCX','CAMS','KFINTECH',
  // === IT & TECH ===
  'TCS','INFY','WIPRO','HCLTECH','TECHM','LTIM',
  'PERSISTENT','COFORGE','MPHASIS','TATAELXSI','LTTS','ECLERX',
  'KPITTECH','BIRLASOFT','CYIENT','ZENSAR','MASTEK','NEWGEN',
  'SONATSOFTW','TANLA','ROUTE','HAPPSTMNDS','DATAPATTNS','AFFLE',
  'TTML','INTELLECT','RATEGAIN','LATENTVIEW','MAPMYINDIA',
  'OFSS','NIITLTD','SASKEN','SUBEXLTD','ORIENTTECH',
  // === PHARMA & HEALTHCARE ===
  'SUNPHARMA','DRREDDY','CIPLA','DIVISLAB','APOLLOHOSP',
  'AUROPHARMA','LAURUSLABS','IPCALAB','NATCOPHARM','GRANULES',
  'AJANTPHARM','TORNTPHARM','ALKEM','BIOCON','GLENMARK',
  'LUPIN','ZYDUSLIFE','ABBOTINDIA','PFIZER','SANOFI',
  'METROPOLIS','LALPATHLAB','THYROCARE','MAXHEALTH','MEDANTA',
  'FORTIS','YATHARTH','ERIS','MANKIND','JBCHEPHARM',
  'SOLARA','SUVEN','LUXPHARMA','GLAND','SHILPAMED',
  'IOLCP','STRIDES','MARKSANS','WOCKPHARMA','PGHH',
  'SUVENPHAR','BLISSGVS','JUBILANT','CAPLIPOINT','FDC',
  // === AUTO & AUTO ANCILLARY ===
  'TATAMOTORS','MARUTI','M&M','BAJAJ-AUTO','EICHERMOT','HEROMOTOCO',
  'ASHOKLEY','TVSMOTOR','BHARATFORG','BALKRISIND','MRF','CEATLTD',
  'APOLLOTYRE','JKTYRE','BOSCHLTD','MOTHERSON','ENDURANCE',
  'SUPRAJIT','SUNDRMFAST','SETCO','CRAFTSMAN','JBMA',
  'EXIDEIND','AMARAJABAT','FIEMIND','LUMAXIND','LUMAXTECH',
  'SWARAJENG','VSTTILLERS','FORCEMOT','OLECTRA','MAHSCOOTER',
  // === FMCG & CONSUMER ===
  'HINDUNILVR','ITC','NESTLEIND','BRITANNIA','TATACONSUM',
  'DABUR','MARICO','GODREJCP','COLPAL','EMAMILTD',
  'VBLINDS','JYOTHYLAB','BIKAJI','ZOMATO','NYKAA',
  'PATANJALI','DMART','TRENT','ABFRL','DEVYANI',
  'SAPPHIRE','CAMPUS','BATAINDIA','RELAXO','METROBRAND',
  'TITAN','RAJESHEXPO','HATSUN','KRBL','USHAMART',
  'TATACOFFEE','CCL','VSTIND','GODFRYPHLP','RADICO',
  'UNITDSPR','EIDPARRY','PRABHAT','VARUNBEV',
  // === METALS & MINING ===
  'TATASTEEL','JSWSTEEL','HINDALCO','COALINDIA','NMDC',
  'VEDL','JINDALSTEL','NATIONALUM','MOIL','HINDZINC',
  'SAIL','RATNAMANI','APLAPOLLO','WELCORP','GALLANTT',
  'SHYAMMETL','LLOYDSME','MIDHANI','KIRLFER','MISSINGNO',
  'TIRUMALCHM','SANDUMA','HLEGLAS','GRAVITA',
  // === OIL & GAS ===
  'RELIANCE','ONGC','BPCL','IOC','HINDPETRO','GAIL',
  'PETRONET','IGL','MGL','GUJGASLTD','ATUL',
  'ATGL','AEGISCHEM','GSPL','CASTROLIND','TIDEWATER',
  // === POWER & ENERGY ===
  'NTPC','POWERGRID','TATAPOWER','ADANIGREEN','ADANIENSO',
  'JSWENERGY','NHPC','SJVN','TORNTPOWER','CESC',
  'JPPOWER','RPOWER','SUZLON','INOXWIND','IREDA',
  'NLCINDIA','KPIGLOBAL','WAREE','ORIENTELEC','GIPCL',
  // === INFRA & CONSTRUCTION ===
  'LT','ADANIPORTS','ADANIENT',
  'NBCC','HCC','IRCON','RVNL','KEC','KALPATPOWR',
  'IRFC','HUDCO','RECLTD','PFC','ENGINERSIN',
  'COCHINSHIP','GRSE','MAZAGON','BDL','BEML','RITES',
  'RAILTEL','GMRAIRPORT','GMRINFRA','PRAJIND','THERMAX',
  'TRITURBINE','ELGIEQUIP','CUMMINSIND','SIEMENS','ABB',
  'HAVELLS','VOLTAS','BLUESTARCO','KAJARIACER',
  'TIINDIA','AIAENG','GRINDWELL',
  // === CEMENT ===
  'ULTRACEMCO','GRASIM','SHREECEM','AMBUJACEM','ACC',
  'DALMIASUGAR','JKCEMENT','RAMCOCEM','STARCEMENT','ORIENTCEM',
  'JKLAKSHMI','HEIDELBERG','BIRLACEM','NUVOCO','SAGCEM',
  'JKCEMENT','PRISMJOHNS','DECCANCEM',
  // === CHEMICALS ===
  'PIDILITIND','AARTIIND','ATUL','NAVINFLUOR','FINEORG',
  'VINATIORGN','DEEPAKFERT','GNFC','GSFC','CHAMBLFERT','RCF',
  'TATACHEM','SUDARSCHEM','CLEAN','SRF','GALAXYSURF',
  'BASF','BAYERCROP','RALLIS','UPL','PIIND',
  'SUMICHEM','BALAXI','NOCIL','ANURAS','ROSSELLIND',
  'ALKYLAMINE','BALAJITELE','LXCHEM','NEOGEN',
  // === TEXTILES & APPAREL ===
  'RAYMOND','ARVIND','TRIDENT','WELSPUNLIV','PGHL',
  'CENTURYTEX','GARFIBRES','HIMATSEIDE','NITINSPINN','SYNGENE',
  'KITEX','DOLLAR','RUPA','LAXMIMACH','FILATEX',
  // === REAL ESTATE ===
  'GODREJPROP','DLF','OBEROIRLTY','BRIGADE','SOBHA',
  'PRESTIGE','LODHA','PHOENIXLTD','SUNTECK','MAHLIFE',
  'KOLTEPATIL','ASHIANA','SIGNATURE','RUSTOMJEE',
  // === MEDIA & ENTERTAINMENT ===
  'PVRINOX','ZEEL','SUNTV','TV18BRDCST','NETWORK18',
  'SAREGAMA','NAZARA','TIPS','DISH','HATHWAY',
  'RADIOCITY','BALAJITELE','SHEMAROO',
  // === TELECOM ===
  'BHARTIARTL','IDEA','TATACOMM','STERLITE','HFCL',
  'TEJAS','ROUTE',
  // === DEFENCE ===
  'HAL','BEL','BDL','MAZAGON','COCHINSHIP','GRSE',
  'BEML','DATAPATTNS','PARAS','DCAL',
  // === RAILWAYS & LOGISTICS ===
  'IRCTC','RVNL','IRFC','IRCON','RITES','RAILTEL',
  'CONCOR','TCI','BLUEDART','DELHIVERY','ALLCARGO',
  'GATI','MAHINDCIE','TVSSRICHAK',
  // === PSU ===
  'SBIN','BANKBARODA','CANARABNK','NTPC','ONGC','COALINDIA',
  'POWERGRID','BPCL','IOC','HINDPETRO','GAIL','NHPC',
  'SJVN','NLCINDIA','NMDC','MOIL','NATIONALUM','SAIL',
  'RECLTD','PFC','HUDCO','IRFC','IRCTC','RVNL','BEL','HAL',
  'CONCOR','NBCC','ENGINERSIN','HPCL','BHEL',
  // === SUGAR ===
  'BALRAMCHIN','RENUKASUG','DHAMPUR','DWARIKESH','TRIVENI',
  'EIDPARRY','DALMIASUG','BAJAJHIND','UGARSUGAR',
  // === MISC SMALL/MID CAPS ===
  'ACMESOLAR','LOKESHMACH','UNIPARTS','GOLDIAM','MCLEODRUSS',
  'SANGINITA','SETCO','MAANALU','CRAFTSMAN','MEGASTAR',
  'SHYAMMETL','LLOYDSME','UNIVCABLES',
  'ABCAPITAL','ICRA','CRISIL','CARERATING',
  // Additional small/mid-caps that commonly appear in scanners
  'GPPL','GESHIP','GMDCLTD','GOCOLORS','GREENPANEL',
  'HAPPSTMNDS','HINDCOPPER','HONAUT','IGPL','INDHOTEL',
  'INDIGOPNTS','ISGEC','JAMNAAUTO','JKPAPER','JUBLFOOD',
  'KALYANKJIL','KANSAINER','KEI','KIRLOSENG','KRSNAA',
  'LAOPALA','MAZDOCK','MFSL','MHRIL','MMTC',
  'MOTILALOFS','NAM-INDIA','NESCO','NORTHARC','OLECTRA',
  'ORIENTELEC','ORIENTCEM','PGEL','PGHH','POLYMED',
  'PRINCEPIPE','PRSMJOHNSN','QUESS','RADICO','REDINGTON',
  'RELAXO','RKFORGE','ROSSELLIND','RVNL','SCHNEIDER',
  'SFL','SGBMINING','SOLARINDS','SPARC','STARCEMENT',
  'SWSOLAR','TATAINVEST','TATVA','TDPOWERSYS','TECHNOE',
  'THYROCARE','TIIL','TITAGARH','TTKPRESTIG','UCOBANK',
  'USHAMART','UTI','VAIBHAVGBL','VALIANTORG','VGUARD',
  'VSTIND','WELCORP','WESTLIFE','WINDMACHIN','ZENSARTECH',
  'ZYDUSWELL','AARTIDRUGS','ACCELYA','AJMERA','ALEMBICLTD',
  'ALLSEC','AMBER','ANANTRAJ','ANDHRAPET','ANGANGROUP',
  'APARINDS','ASHIANA','ASTEC','AURIONPRO','AVANTIFEED',
  'AXISCADES','BANARISUG','BLS','CANFINHOME','CARTRADE',
  'CGPOWER','CHEMCON','CHEMPLASTS','CHOICEIN','CIGNITITEC',
  'CreditAcc','DCBBANK','DCMSHRIRAM','DEEPAKNITRI','DELTACORP',
  'DEVYANI','DREAMFOLKS','ELECON','EPL','EQUITASBNK',
  'FINOLEX','FIVESTAR','FLUOROCHEM','GICRE','GLS',
  'GNFC','GODFRYPHLP','GODREJIND','GOKEX','GPIL',
  'GRINDWELL','GSFC','GULFOILLUB','HBLPOWER','HERANBA',
  'HINDWAREAP','HMVL','HOMEFIRST','HUDCO','IBREALEST',
  'IFBIND','INDIACEM','INDIAMART','INDIGOPAINTS','INOXGREEN',
  'IRCON','ITDCEM','JAYNECOIND','JCHAC','JINDALSAW',
  'JISLJALEQS','JKTYRE','JMFINANCIL','JSWINFRA','JTEKTINDIA',
  'JUSTDIAL','KAJARIACER','KAYNES','KESORAMIND','KIMS',
  'KIRLOSIND','KRBL','KSB','LAXMIMACH','LEMONTREE',
  'LINDEINDIA','LTFOODS','LUXIND','MAHLOG','MAHSEAMLESS',
  'MAITHANALL','MAPMYINDIA','MASTEK','MAXHEALTH','MEDANTA',
  'MEDPLUS','METROPOLIS','MIDHANI','MINDACORP','MMFL',
  'MOLDTKPAC','MRPL','MSTCLTD','MTARTECH','MUTHOOTFIN',
  'NATCOPHARM','NBCC','NELCO','NETWORK18','NEWGEN',
  'NH','NIACL','NIITLTD','NUVOCO','PARAS',
  'PARADEEP','PATANJALI','PEL','PGHL','PIIND',
  'PNBGILTS','PNCINFRA','POWERMECH','PRECWIRE','PRICOLLTD',
  'PVRINOX','RAINBOW','RAJESHEXPO','RALLIS','RTNINDIA',
  'RVNL','SAFARI','SARDAEN','SATIN','SCHAEFFLER',
  'SHILPAMED','SHOPERSTOP','SHYAMMETL','SJVN','SOBHA',
  'SOLARA','SPARC','STARHEALTH','STLTECH','SUNFLAG',
  'SUNTECK','SUPRAJIT','SURYAROSNI','SWANENERGY','SYMPHONY',
  'TARSONS','TASTYBITE','TATAINVEST','TATVA','TCIEXP',
  'TEAMLEASE','TECHNOE','THYROCARE','TITAGARH','TRENT',
  'TRITURBINE','TV18BRDCST','UJJIVANSFB','VAKRANGEE','VIPIND',
  'WABAG','WINDMACHIN','WONDERLA','YATHARTH','ZENSARTECH',
];

// Remove duplicates
const seen = new Set<string>();
export const NSE_UNIQUE: string[] = NSE_UNIVERSE.filter(s => {
  if (seen.has(s)) return false;
  seen.add(s);
  return true;
});
