import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { NSE_UNIQUE } from "../server/nseUniverse.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const manualMap: Record<string, string> = {
  "reliance industries": "RELIANCE",
  "reliance": "RELIANCE",
  "tata consultancy services": "TCS",
  "tata consultancy": "TCS",
  "tcs": "TCS",
  "hdfc bank": "HDFCBANK",
  "hdfc": "HDFCBANK",
  "infosys": "INFY",
  "icici bank": "ICICIBANK",
  "icici": "ICICIBANK",
  "hindustan unilever": "HINDUNILVR",
  "hind unilever": "HINDUNILVR",
  "hul": "HINDUNILVR",
  "state bank of india": "SBIN",
  "state bank": "SBIN",
  "sbi": "SBIN",
  "bharti airtel": "BHARTIARTL",
  "airtel": "BHARTIARTL",
  "kotak mahindra": "KOTAKBANK",
  "kotak": "KOTAKBANK",
  "larsen & toubro": "LT",
  "larsen and toubro": "LT",
  "l&t": "LT",
  "axis bank": "AXISBANK",
  "axis": "AXISBANK",
  "hcl technologies": "HCLTECH",
  "hcl tech": "HCLTECH",
  "titan company": "TITAN",
  "titan": "TITAN",
  "bajaj finance": "BAJFINANCE",
  "asian paints": "ASIANPAINT",
  "maruti suzuki": "MARUTI",
  "maruti": "MARUTI",
  "sun pharmaceutical": "SUNPHARMA",
  "sun pharma": "SUNPHARMA",
  "nestle india": "NESTLEIND",
  "nestle": "NESTLEIND",
  "tata motors": "TATAMOTORS",
  "wipro": "WIPRO",
  "ntpc": "NTPC",
  "power grid": "POWERGRID",
  "ultratech cement": "ULTRACEMCO",
  "ultratech": "ULTRACEMCO",
  "adani ports": "ADANIPORTS",
  "tata steel": "TATASTEEL",
  "oil & natural gas": "ONGC",
  "ongc": "ONGC",
  "jsw steel": "JSWSTEEL",
  "tech mahindra": "TECHM",
  "indusind bank": "INDUSINDBK",
  "indusind": "INDUSINDBK",
  "bajaj auto": "BAJAJ-AUTO",
  "mahindra & mahindra": "M&M",
  "m&m": "M&M",
  "coal india": "COALINDIA",
  "dr reddy": "DRREDDY",
  "bpcl": "BPCL",
  "bharat petroleum": "BPCL",
  "cipla": "CIPLA",
  "grasim industries": "GRASIM",
  "grasim": "GRASIM",
  "adani enterprises": "ADANIENT",
  "apollo hospitals": "APOLLOHOSP",
  "eicher motors": "EICHERMOT",
  "eicher": "EICHERMOT",
  "hero motocorp": "HEROMOTOCO",
  "hero honda": "HEROMOTOCO",
  "divi's laboratories": "DIVISLAB",
  "divis lab": "DIVISLAB",
  "tata consumer products": "TATACONSUM",
  "tata consumer": "TATACONSUM",
  "hindalco industries": "HINDALCO",
  "hindalco": "HINDALCO",
  "sbi life insurance": "SBILIFE",
  "sbi life": "SBILIFE",
  "bajaj finserv": "BAJAJFINSV",
  "hdfc life insurance": "HDFCLIFE",
  "hdfc life": "HDFCLIFE",
  "britannia industries": "BRITANNIA",
  "britannia": "BRITANNIA",
  "shriram finance": "SHRIRAMFIN",
  "ltimindtree": "LTIM",
  "ltim": "LTIM",
  "trent": "TRENT",
  "zomato": "ZOMATO",
  "nykaa": "NYKAA",
  "fsn e-commerce": "NYKAA",
  "jio financial": "JIOFIN",
  "interglobe aviation": "INDIGO",
  "indigo": "INDIGO",
  "hal": "HAL",
  "hindustan aeronautics": "HAL",
  "bel": "BEL",
  "bharat electronics": "BEL",
  "rec": "RECLTD",
  "rural electrification": "RECLTD",
  "pfc": "PFC",
  "power finance": "PFC",
  "dlf": "DLF",
  "vedanta": "VEDL",
  "tata power": "TATAPOWER",
  "shree cement": "SHREECEM",
  "ambuja cements": "AMBUJACEM",
  "ambuja": "AMBUJACEM",
  "acc": "ACC",
  "godrej properties": "GODREJPROP",
  "godrej": "GODREJPROP",
  "havells": "HAVELLS",
  "pidilite": "PIDILITIND",
  "dabur": "DABUR",
  "marico": "MARICO",
  "colgate": "COLPAL",
  "colgate-palmolive": "COLPAL",
  "united spirits": "UNITDSPR",
  "mcdowell": "UNITDSPR",
  "varun beverages": "VBLINDS",
  "vbl": "VBLINDS",
  "tata communications": "TATACOMM",
  "lupin": "LUPIN",
  "aurobindo pharma": "AUROPHARMA",
  "biocon": "BIOCON",
  "glenmark": "GLENMARK",
  "torrent pharmaceuticals": "TORNTPHARM",
  "torrent pharma": "TORNTPHARM",
  "alkem laboratories": "ALKEM",
  "alkem": "ALKEM",
  "zydus life": "ZYDUSLIFE",
  "cadila": "ZYDUSLIFE",
  "ashok leyland": "ASHOKLEY",
  "tvs motor": "TVSMOTOR",
  "bharat forge": "BHARATFORG",
  "balkrishna industries": "BALKRISIND",
  "mrf": "MRF",
  "ceat": "CEATLTD",
  "apollo tyres": "APOLLOTYRE",
  "jk tyre": "JKTYRE",
  "bosch": "BOSCHLTD",
  "exide": "EXIDEIND",
  "amara raja": "AMARAJABAT",
  "suzlon": "SUZLON",
  "sail": "SAIL",
  "steel authority": "SAIL",
  "jindal steel": "JINDALSTEL",
  "jindal": "JINDALSTEL",
  "national aluminium": "NATIONALUM",
  "nalco": "NATIONALUM",
  "hindustan zinc": "HINDZINC",
  "gail": "GAIL",
  "indraprastha gas": "IGL",
  "igl": "IGL",
  "mahanagar gas": "MGL",
  "mgl": "MGL",
  "gujarat gas": "GUJGASLTD",
  "petronet lng": "PETRONET",
  "petronet": "PETRONET",
  "adani green": "ADANIGREEN",
  "adani power": "ADANIPOWER",
  "jsw energy": "JSWENERGY",
  "nhpc": "NHPC",
  "sjvn": "SJVN",
  "torrent power": "TORNTPOWER",
  "nbcc": "NBCC",
  "irctc": "IRCTC",
  "rvnl": "RVNL",
  "rail vikas": "RVNL",
  "irfc": "IRFC",
  "indian railway finance": "IRFC",
  "ircon": "IRCON",
  "rites": "RITES",
  "railtel": "RAILTEL",
  "concor": "CONCOR",
  "container corporation": "CONCOR",
  "bhel": "BHEL",
  "bharat heavy electricals": "BHEL",
  "mazaon dock": "MAZAGON",
  "mazagon dock": "MAZAGON",
  "cochin shipyard": "COCHINSHIP",
  "garden reach": "GRSE",
  "grse": "GRSE",
  "voltas": "VOLTAS",
  "blue star": "BLUESTARCO",
  "siemens": "SIEMENS",
  "abb india": "ABB",
  "abb": "ABB",
  "cummins": "CUMMINSIND",
  "thermax": "THERMAX",
  "escorts": "ESCORTS",
  "escorts kubota": "ESCORTS",
  "muthoot finance": "MUTHOOTFIN",
  "manappuram": "MANAPPURAM",
  "cholamandalam": "CHOLAFIN",
  "chola": "CHOLAFIN",
  "lic housing": "LICHSGFIN",
  "can fin homes": "CANFINHOME",
  "aavas financiers": "AAVAS",
  "angel one": "ANGANGROUP",
  "motilal oswal": "MOTILALOFS",
  "jm financial": "JMFINANCIL",
  "bse": "BSE",
  "cdsl": "CDSL",
  "mcx": "MCX",
  "cams": "CAMS",
  "kfin technologies": "KFINTECH",
  "kfintech": "KFINTECH",
  "lic of india": "LICI",
  "lic": "LICI",
  "star health": "STARHEALTH",
  "gici": "GICRE",
  "general insurance corporation": "GICRE",
  "new india assurance": "NIACL",
  "niacl": "NIACL",
  "pidilite industries": "PIDILITIND",
  "aarti industries": "AARTIIND",
  "aarti": "AARTIIND",
  "atul": "ATUL",
  "navin fluorine": "NAVINFLUOR",
  "deepak nitrite": "DEEPAKNITRI",
  "chambal fertilisers": "CHAMBLFERT",
  "rashtriya chemicals": "RCF",
  "rcf": "RCF",
  "tata chemicals": "TATACHEM",
  "upl": "UPL",
  "pi industries": "PIIND",
  "sumitomo chemical": "SUMICHEM",
  "raymond": "RAYMOND",
  "arvind": "ARVIND",
  "trident": "TRIDENT",
  "welspun living": "WELSPUNLIV",
  "century textiles": "CENTURYTEX",
  "oberoi realty": "OBEROIRLTY",
  "oberoi": "OBEROIRLTY",
  "brigade enterprises": "BRIGADE",
  "brigade group": "BRIGADE",
  "sobha": "SOBHA",
  "prestige estates": "PRESTIGE",
  "prestige": "PRESTIGE",
  "lodha": "LODHA",
  "macrotech": "LODHA",
  "phoenix mills": "PHOENIXLTD",
  "pvr inox": "PVRINOX",
  "pvr": "PVRINOX",
  "zee entertainment": "ZEEL",
  "zeel": "ZEEL",
  "sun tv": "SUNTV",
  "tv18": "TV18BRDCST",
  "network18": "NETWORK18",
  "saregama": "SAREGAMA",
  "nazara technologies": "NAZARA",
  "nazara": "NAZARA",
  "vodafone idea": "IDEA",
  "idea": "IDEA",
  "sterlite technologies": "STERLITE",
  "tejas networks": "TEJASNET",
  "route mobile": "ROUTE",
  "irctc ltd": "IRCTC",
  "ireda": "IREDA",
  "indian renewable energy": "IREDA"
};

const finalMap: Record<string, string> = { ...manualMap };

for (const symbol of NSE_UNIQUE) {
  const lowerSymbol = symbol.toLowerCase();
  
  if (!finalMap[lowerSymbol]) {
    finalMap[lowerSymbol] = symbol;
  }
  
  finalMap[`${lowerSymbol} share`] = symbol;
  finalMap[`${lowerSymbol} shares`] = symbol;
  finalMap[`${lowerSymbol} stock`] = symbol;
  finalMap[`${lowerSymbol} ltd`] = symbol;
  finalMap[`${lowerSymbol} limited`] = symbol;
  
  if (lowerSymbol.includes("-")) {
    const spaceVer = lowerSymbol.replace(/-/g, " ");
    finalMap[spaceVer] = symbol;
    finalMap[`${spaceVer} share`] = symbol;
  }
}

writeFileSync(
  join(__dirname, "../server/companyNameMap.json"),
  JSON.stringify(finalMap, null, 2),
  "utf8"
);
console.log(`Successfully generated company name map with ${Object.keys(finalMap).length} keys!`);
